"""
Dockerfile Generator — creates Dockerfile content based on detected stack.
"""

import json

def generate_dockerfile(stack: str, repo_files: dict, repo_url: str) -> str:
    """
    Generate Dockerfile content for the detected stack.
    """
    generators = {
        "node": _node_dockerfile,
        "python": _python_dockerfile,
        "go": _go_dockerfile,
        "rust": _rust_dockerfile,
        "ruby": _ruby_dockerfile,
        "static": _static_dockerfile,
        "docker": _docker_existing,
    }
    
    generator = generators.get(stack, _static_dockerfile)
    return generator(repo_files, repo_url)

def _node_dockerfile(repo_files: dict, repo_url: str) -> str:
    pkg = json.loads(repo_files.get("package.json", "{}"))
    scripts = pkg.get("scripts", {})
    dependencies = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
    
    # Determine node version
    engines = pkg.get("engines", {})
    node_version = engines.get("node", "18")
    if node_version.startswith(">=") or node_version.startswith("^"):
        node_version = node_version.lstrip(">=^")
    node_version = node_version.split(".")[0]  # major version only
    
    # Determine build/start
    has_build = "build" in scripts
    start_cmd = scripts.get("start", "node server.js")
    
    # Framework-specific tweaks
    if "next" in dependencies:
        start_cmd = "npm start"
    elif "nuxt" in dependencies or "nuxt3" in dependencies:
        start_cmd = "node .output/server/index.mjs"
    
    dockerfile = f"""# Node.js {node_version} — Auto-generated by Deploy Button Generator
FROM node:{node_version}-alpine

WORKDIR /app

# Copy dependency files
COPY package*.json ./
RUN npm ci --only=production

# Copy source
COPY . .
"""
    
    if has_build:
        dockerfile += "RUN npm run build\n"
    
    dockerfile += f"""
# Expose and run
EXPOSE 3000
CMD ["{start_cmd.split()[0]}", "{(' '.join(start_cmd.split()[1:]) if len(start_cmd.split()) > 1 else '')}"]
"""
    
    # Clean up the CMD line if it's simple
    if start_cmd == "npm start":
        dockerfile = dockerfile.replace('CMD ["npm", "start"]\n', 'CMD ["npm", "start"]\n')
    
    return dockerfile.strip()

def _python_dockerfile(repo_files: dict, repo_url: str) -> str:
    req_content = repo_files.get("requirements.txt", "")
    
    # Detect framework
    if "fastapi" in req_content.lower():
        framework = "fastapi"
        start_cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"
    elif "flask" in req_content.lower():
        framework = "flask"
        start_cmd = "flask run --host=0.0.0.0 --port=8000"
    elif "django" in req_content.lower():
        framework = "django"
        start_cmd = "gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    else:
        framework = "generic"
        start_cmd = "python app.py"
    
    return f"""# Python 3.11 — Auto-generated by Deploy Button Generator
FROM python:3.11-slim

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Expose and run
EXPOSE 8000
CMD ["{start_cmd}"]
""".strip()

def _go_dockerfile(repo_files: dict, repo_url: str) -> str:
    return """# Go — Auto-generated by Deploy Button Generator
# Multi-stage build for minimal image
FROM golang:1.21-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

# Final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /build/app .

EXPOSE 8080
CMD ["./app"]
""".strip()

def _rust_dockerfile(repo_files: dict, repo_url: str) -> str:
    return """# Rust — Auto-generated by Deploy Button Generator
# Multi-stage build for minimal image
FROM rust:1.75-slim AS builder

WORKDIR /build
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release && rm -rf src

COPY . .
RUN cargo build --release

# Final stage
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /build/target/release/* ./

EXPOSE 8080
CMD ["./app"]
""".strip()

def _ruby_dockerfile(repo_files: dict, repo_url: str) -> str:
    gemfile = repo_files.get("Gemfile", "")
    if "rails" in gemfile.lower():
        start_cmd = "bundle exec rails server -b 0.0.0.0"
    else:
        start_cmd = "ruby app.rb"
    
    return f"""# Ruby — Auto-generated by Deploy Button Generator
FROM ruby:3.2-slim

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application
COPY . .

# Expose and run
EXPOSE 3000
CMD ["{start_cmd}"]
""".strip()

def _static_dockerfile(repo_files: dict, repo_url: str) -> str:
    return """# Static Site — Auto-generated by Deploy Button Generator
FROM nginx:alpine

# Copy static files to nginx html directory
COPY . /usr/share/nginx/html/

# Simple nginx config for SPA routing
RUN echo 'server { \\
    listen 80; \\
    location / { \\
        root /usr/share/nginx/html; \\
        index index.html; \\
        try_files $uri $uri/ /index.html; \\
    } \\
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
""".strip()

def _docker_existing(repo_files: dict, repo_url: str) -> str:
    return """# Dockerfile already exists in this repo!
# The existing Dockerfile will be used for deployment.
# No changes needed — you're good to go.

# (If you want to review it, check the Dockerfile in your repo root)
""".strip()
